### ISSUE TITLE
homework/2.7.1 Сравнение массивов

### ISSUE THREAD

**Issue by sautin1** [Shamil0402/1c-front-end#1]
Привет!
1) Назови папку именем "2.7.1. Sravnenie massivov" или как-то схожим образом. Чтобы, глядя на имя папки, был виден номер задания и было понятно, о чем оно.
2) В цикле стоит неверное условие окончания.
3) Функция не проходит такой тест:
```javascript
> check([1], [1])
true
> check([1], [2])
false
```
4) *Лучше давать функциям более осмысленные названия, чтобы по их названию можно было догадаться, что они делают. Например, твоей функции check больше бы подошло название areArraysEqual, которое предлагается в учебнике.  

__
\* пункты со звездочкой - это требования, не обязательные для сдачи задания, но очень желательные для твоего саморазвития как программиста.

**Comment by Shamil0402** [comment]
![image](https://cloud.githubusercontent.com/assets/10086234/22847849/efedc97a-f000-11e6-87fd-f24538395931.png)
У меня проходит)

**Comment by sautin1** [comment]
Да, я ошибся, извини. Надо поменять местами вызовы, тогда работает неверно:
```javascript
> check([1], [2])
false
> check([1], [1])
false
```

**Comment by Shamil0402** [comment]
Теперь вроде работает)

**Comment by sautin1** [comment]
Да, теперь работает. :)
Давай ты еще поправишь условие окончания цикла (пункт 2) и уже точно приму задачку. ;)
P.S. можешь заодно убрать свои глобальные массивы a и b, все равно они никак не используются. :)

**Comment by Shamil0402** [comment]
Fixed

**Comment by sautin1** [comment]
Молодец! Спасибо, что учел все мои замечания! Задачка зачтена ;)
