### ISSUE TITLE
homework/1.6.1 Часы

### ISSUE THREAD

**Issue by sautin1** [Shamil0402/1c-front-end#2]
Привет!
Молодец, что практически полностью разобрался с этим заданием. Оно непростое. ;)

**Замечания:**
1) Зачем тебе отдельный контекст cifri? Почему бы не рисовать все в контексте context? Из-за этого у тебя и стрелочки не стираются, ты же их рисуешь в контексте cifri, а clearRect вызываешь только для контекста context.  
2) Нужен еще циферблат часов - окружность вокруг всего этого счастья.  
3) \* Чтобы не получались такие длинные функции, как твой drawWatch, лучше разбивать ее на несколько более мелких логически законченных функций. Например, в этом случае можно было написать такие отдельные функции:
- функция, рисующая стрелочки;
- функция, рисующая засечки;
и вызвать их из drawWatch.

__
\* пункты со звездочкой - это требования, не обязательные для сдачи задания, но очень желательные для твоего саморазвития как программиста.

**Comment by Shamil0402** [comment]
Функция разбита на несколько более мелких, добавлена окружность.
Но удаление контекста не помогло...

**Comment by sautin1** [comment]
Я пока не понял, в чем проблема. Буду разбираться еще :)

**Comment by Shamil0402** [comment]
Fixed

**Comment by sautin1** [comment]
Мне кажется, ты не запускал свой код перед тем, как писать тут "Fixed" :)
Проблема со стрелками все еще присутствует.

**Comment by Shamil0402** [comment]
Я же сохранил и коммитнул!
Кто обратно вернул????

**Comment by sautin1** [comment]
В твоем последнем коммите ты действительно делаешь исправления, похожие на те, что мы обсуждали. Но все же не те :)

**Comment by Shamil0402** [comment]
Возможно я сначала нажал sync и перезаписал все свои файлы и потом коммитнул и опять sync...

**Comment by Shamil0402** [comment]
Теперь точно должно работать
![image](https://cloud.githubusercontent.com/assets/10086234/23319776/05ee98f6-fae9-11e6-82a3-33d93055f59c.png)

**Comment by Shamil0402** [comment]
fixed again

**Comment by Shamil0402** [comment]
Забыл нажать sync

**Comment by sautin1** [comment]
Теперь работает корректно. Но есть несколько необязательных замечаний:

1) `circle = new Path2D();` -- где объявляется (создается) эта переменная?
2) Почему бы не внести объявление переменной `var square;` внутрь функции `drawCiferblat`? Она же только там используется.
3) Ты внес объявление переменных `var minute, hour, second` внутрь функции `drawStrelka`. Это верно. Но тогда зачем тебе их объявлять до этого как глобальные переменные в 5-7 строчках?

**Comment by Shamil0402** [comment]
Fixed neobyazatelnie zamechaniya

**Comment by sautin1** [comment]
Красавчик! :) Засчитано!
