### ISSUE TITLE
homework/2.7.2 wordcount

### ISSUE THREAD

**Issue by sautin1** [Shamil0402/1c-front-end#3]
Привет, Шамиль!
Ты правильно составил список слов splitted. Теперь нужно преобразовать этот список так, чтобы в нем остались только длинные слова (больше 4-х символов).

После этого не нужно вручную заполнять mnojestvo, а надо для каждого слова из списка вызвать функцию addWord, которая построит словарь слов и их частот.

После этого необходимо пройти по полученному словарю и найти слово с максимальной частотой.

**Comment by Shamil0402** [comment]
fixed

**Comment by sautin1** [comment]
Вот читаю я твой код, радуюсь, что ты все правильно делаешь :) А в конце досадная ошибка, из-за которой результат неправильный :(((
По делу:
1) Посмотри на то, как ты ищешь слово с максимальной частотой в словаре dictionary. Там есть 2 ошибки.
2) Ожидалось, что массив longwords ты будешь заполнять с помощью функции filter.
3) Ожидалось, что функцию addWords ты будешь вызывать, используя функцию forEach.
4) \* Смотри, у тебя все переменные, которые ты объявил в начале файла (кроме button) используются только внутри функции calc. Почему бы и не объявить их внутри этой функции? Тогда они будут автоматически создаваться заново (и обнуляться) при каждом вызове функции и не придется вручную делать всякие обнуления:
```javascript
longwords = [];
dictionary = {};
splitted = [];
```

**Comment by Shamil0402** [comment]
![image](https://cloud.githubusercontent.com/assets/10086234/23319880/6fd9a9fe-fae9-11e6-88c5-71ab58ed7dc7.png)
Эти?)))

**Comment by sautin1** [comment]
Ага, конечно :) И отступ не забудь :)

**Comment by Shamil0402** [comment]
Fixed again))))))

**Comment by Shamil0402** [comment]
Четвёртый пункт тоже

**Comment by Shamil0402** [comment]
Fixed again again

**Comment by sautin1** [comment]
Level Up! :)
